import { ArrowRight, BookOpen, GitBranch, Layers3 } from "lucide-react";
import { useState } from "react";
import { conceptLessons, methodLessons } from "../../data/learningArchitecture";
import type { ConceptLessonV1 } from "../../domain/learningArchitecture";
import { useAppStore } from "../../state/store";

function HierarchyExplorer() {
  const [selected, setSelected] = useState<"patient" | "sample" | "cell">();
  return <section className="hierarchy-explorer"><header><Layers3/><div><strong>Hierarchy Explorer</strong><span>目标推断：比较两组患者</span></div></header><div className="hierarchy-tree">{[1, 2].map((patient) => <article key={patient} className={selected === "patient" ? "selected-level" : ""}><button onClick={() => setSelected("patient")}>Patient {patient}</button>{["A", "B"].map((sample) => <div key={sample} className={selected === "sample" ? "selected-level" : ""}><button onClick={() => setSelected("sample")}>Sample {sample}</button><div className={selected === "cell" ? "selected-level cells" : "cells"}>{[1, 2, 3].map((cell) => <button key={cell} onClick={() => setSelected("cell")}>Cell {cell}</button>)}</div></div>)}</article>)}</div>{selected && <div className={`hierarchy-explanation ${selected === "patient" ? "correct" : ""}`}>{selected === "patient" ? "患者层级支持患者组间推断。每位患者贡献一个独立来源。" : selected === "cell" ? "这些细胞按患者聚集并共享来源；更多细胞提高患者内测量精度，但不会创造更多独立患者。" : "组织块仍嵌套在患者内。它能描述取样变异，但患者组间推断仍需在患者层级处理依赖。"}</div>}</section>;
}

function ConceptSurface({ lesson, onStandardizedApply }: { lesson: ConceptLessonV1; onStandardizedApply: () => void }) {
  const [phase, setPhase] = useState<"learn" | "explain" | "apply" | "remediation">("learn");
  const [explanation, setExplanation] = useState("");
  const [applyReasoning, setApplyReasoning] = useState("");
  const [locked, setLocked] = useState(false);
  return <section className="concept-surface"><header><span className="eyebrow">Concept Lesson · Learn → Explain → Apply</span><h1>{lesson.titleCn}</h1><p>{lesson.titleEn}</p><nav>{["learn", "explain", "apply"].map((item) => <button key={item} className={phase === item ? "active" : ""} onClick={() => setPhase(item as typeof phase)}>{item}</button>)}</nav></header>{phase === "learn" && <div className="coherent-lesson"><article><strong>Why it matters</strong><p>{lesson.whyItMattersCn}</p></article><article><strong>Intuition</strong><p>{lesson.intuitionCn}</p></article><article><strong>Precise explanation</strong><p>{lesson.preciseExplanationCn}</p></article><article><strong>Worked example</strong><p>{lesson.workedExampleCn}</p></article>{lesson.interaction === "hierarchy_explorer" && <HierarchyExplorer/>}{lesson.interaction === "dag_placeholder" && <div className="dag-placeholder"><GitBranch/><span>疾病严重度 → 治疗选择</span><span>疾病严重度 → 结局</span><small>先声明结构假设，再决定调整。</small></div>}<button className="primary" onClick={() => setPhase("explain")}>用自己的话解释 <ArrowRight size={14}/></button></div>}{phase === "explain" && <div className="explain-phase"><h2>{lesson.explainPromptCn}</h2><textarea rows={6} value={explanation} onChange={(event) => setExplanation(event.target.value)} placeholder="写 1–3 句；系统不会伪造精确 AI 分数。"/><details><summary>完整解释通常应包含…</summary><ul>{lesson.explanationChecklistCn.map((item) => <li key={item}>{item}</li>)}</ul></details><button className="primary" disabled={explanation.trim().length < 12} onClick={() => setPhase("apply")}>进入新案例</button></div>}{phase === "apply" && <div className="apply-phase"><span className="eyebrow">Exactly one fresh Apply case</span><h2>{lesson.conceptId === "statistical-unit" ? "两组各 6 名患者；每人两个组织块，每块 20 个 ROI。患者组间比较的主要统计单位是什么？为什么？" : "观察研究中疾病严重度同时影响治疗选择和结局。你会如何界定目标问题与混杂控制？"}</h2><textarea rows={6} disabled={locked} value={applyReasoning} onChange={(event) => setApplyReasoning(event.target.value)} placeholder="写出结构化判断、理由和主张边界。"/>{!locked ? <button className="primary" disabled={applyReasoning.trim().length < 20} onClick={() => setLocked(true)}>锁定回答</button> : <div className="self-compare"><strong>先自我比较，不自动判定 mastery</strong><ul>{lesson.explanationChecklistCn.map((item) => <li key={item}>{item}</li>)}</ul><div><button className="primary" onClick={onStandardizedApply}>进入版本化标准 Apply</button><button onClick={() => setPhase("remediation")}>我需要补救</button></div></div>}</div>}{phase === "remediation" && <div className="remediation"><h2>Adaptive Remediation</h2><p>{lesson.conceptId === "statistical-unit" ? "容易混淆的点是：观测数量不等于独立来源数量。先把所有 ROI 按患者重新分组，再问患者组间差异由多少个独立来源支持。" : "容易混淆的点是：变量与暴露和结局相关并不足以决定调整。先区分共同原因、中介和碰撞点。"}</p><button onClick={() => { setLocked(false); setApplyReasoning(""); setPhase("apply"); }}>尝试第二个新表面案例</button></div>}</section>;
}

export function LearningArchitectureView({ onOpenLegacy }: { onOpenLegacy: () => void }) {
  const [selectedId, setSelectedId] = useState(conceptLessons[0].id);
  const start = useAppStore((state) => state.startLearningUnit);
  const selectedConcept = conceptLessons.find((item) => item.id === selectedId);
  const selectedMethod = methodLessons.find((item) => item.id === selectedId);
  const standardizedApply = () => {
    if (selectedConcept?.conceptId === "statistical-unit") { start("lu-statistical-unit-v1", "challenge"); onOpenLegacy(); }
  };
  return <div className="learn-architecture"><aside><span className="eyebrow">LEARN</span><h2>Foundation Spine</h2>{conceptLessons.map((lesson) => <button key={lesson.id} className={lesson.id === selectedId ? "active" : ""} onClick={() => setSelectedId(lesson.id)}><BookOpen size={14}/><span>{lesson.titleCn}<small>Concept Lesson</small></span></button>)}<h2>Project Overlay</h2>{methodLessons.map((lesson) => <button key={lesson.id} className={lesson.id === selectedId ? "active" : ""} onClick={() => setSelectedId(lesson.id)}><Layers3 size={14}/><span>{lesson.titleCn}<small>Method Lesson</small></span></button>)}<button className="subtle" onClick={onOpenLegacy}>查看 M017 兼容学习记录</button></aside><main className="scrollable">{selectedConcept && <ConceptSurface lesson={selectedConcept} onStandardizedApply={standardizedApply}/>} {selectedMethod && <section className="method-lesson"><header><span className="eyebrow">Method Lesson · method-specific structure</span><h1>{selectedMethod.titleCn}</h1><p>{selectedMethod.titleEn}</p></header><article><h2>Scientific question</h2><p>{selectedMethod.scientificQuestionCn}</p></article><div className="method-grid"><article><h3>Input</h3><ul>{selectedMethod.inputsCn.map((item) => <li key={item}>{item}</li>)}</ul></article><article><h3>Output</h3><ul>{selectedMethod.outputsCn.map((item) => <li key={item}>{item}</li>)}</ul></article></div><article><h2>Core logic</h2><p>{selectedMethod.coreLogicCn}</p></article><article><h2>Critical assumptions</h2><ul>{selectedMethod.assumptionsCn.map((item) => <li key={item}>{item}</li>)}</ul></article><div className="method-grid"><article><h3>Appropriate when</h3><ul>{selectedMethod.appropriateWhenCn.map((item) => <li key={item}>{item}</li>)}</ul></article><article><h3>Not appropriate when</h3><ul>{selectedMethod.inappropriateWhenCn.map((item) => <li key={item}>{item}</li>)}</ul></article></div><article><h2>Common misuse</h2><ul>{selectedMethod.misusePatternsCn.map((item) => <li key={item}>{item}</li>)}</ul></article><article><h2>Reviewer checks</h2><ul>{selectedMethod.reviewerChecksCn.map((item) => <li key={item}>{item}</li>)}</ul></article><article><h2>How it appears in a paper</h2><p>{selectedMethod.paperAppearanceCn}</p></article><section className="method-apply"><span className="eyebrow">Apply · Methods audit</span><p>{selectedMethod.applyPromptCn}</p></section></section>}</main></div>;
}
