import { ArrowRight, BookOpen, Brain, CalendarDays, CheckCircle2, Lightbulb, RotateCcw } from "lucide-react";
import { useState } from "react";
import { useShallow } from "zustand/react/shallow";
import { ThinkBeforeAi } from "../../components/ThinkBeforeAi";
import { generateTodayTasks } from "../../learning/scheduler";
import { useAppStore } from "../../state/store";

export function TodayView(){
  const state=useAppStore(useShallow((s)=>({schemaVersion:s.schemaVersion,papers:s.papers,projects:s.projects,responses:s.responses,reviewItems:s.reviewItems,reviewLogs:s.reviewLogs,skillEvidence:s.skillEvidence,providers:s.providers,settings:s.settings,completedTaskIds:s.completedTaskIds,snoozedTaskIds:s.snoozedTaskIds,assessmentHistory:s.assessmentHistory,notesByPaperId:s.notesByPaperId,draftResponses:s.draftResponses,misconceptions:s.misconceptions,onboarding:s.onboarding,problemAtlasSources:s.problemAtlasSources,problemAtlasClaims:s.problemAtlasClaims,problemCards:s.problemCards,diagnosticCauses:s.diagnosticCauses,diagnosticChecks:s.diagnosticChecks,diagnosticPaths:s.diagnosticPaths,diagnosticEvidence:s.diagnosticEvidence,problemTrainingCases:s.problemTrainingCases,diagnosticSessions:s.diagnosticSessions,sourcePackImports:s.sourcePackImports,problemSearchLog:s.problemSearchLog,personalContent:s.personalContent,contentRevisionHistory:s.contentRevisionHistory,contentConflicts:s.contentConflicts,learnerUnitStates:s.learnerUnitStates,learningEvents:s.learningEvents,pausedLearningUnitIds:s.pausedLearningUnitIds,lessonProgressByUnitId:s.lessonProgressByUnitId,routineSettings:s.routineSettings,routineLogs:s.routineLogs,reasoningRecords:s.reasoningRecords,paperCards:s.paperCards,obsidianConnection:s.obsidianConnection,obsidianPublishBatches:s.obsidianPublishBatches})));
  const setView=useAppStore((s)=>s.setView),selectUnit=useAppStore((s)=>s.selectLearningUnit),selectPaper=useAppStore((s)=>s.selectPaper),recordRoutine=useAppStore((s)=>s.recordRoutine); const[thinking,setThinking]=useState(false);
  const tasks=generateTodayTasks(state),due=tasks.find((t)=>["delayed_retrieval","far_transfer"].includes(t.learningActivityType??"")),core=tasks.find((t)=>t.id!==due?.id),weekAgo=Date.now()-7*86400000,weekLogs=state.routineLogs.filter((x)=>Date.parse(x.occurredAt)>=weekAgo),paperCount=weekLogs.filter((x)=>x.routineType==="paper_reading"&&x.status==="completed").length;
  const start=(task:NonNullable<typeof core>)=>task.type==="learning"?selectUnit(task.targetId):setView(task.destination);
  return <div className="page today-plan"><header className="page-header today-header"><div><span className="eyebrow">Today's Research Training Plan</span><h1>今天推进一个真正的科研认知步骤</h1><p>先学习，再练习；需要 AI 时，先留下自己的判断。</p></div><div className="today-date"><CalendarDays/><span>{new Intl.DateTimeFormat("zh-CN",{month:"short",day:"numeric",weekday:"short"}).format(new Date())}</span></div></header>
    <div className="today-plan-grid"><section className="today-core"><span className="plan-label">A · Today's Core</span>{core?<><h2>{core.title}</h2><p>{core.subtitle}</p><div className="recommendation-why"><strong>为什么今天学这个</strong><span>{core.rationale}。完成后，你会更能识别研究问题与独立信息层级是否一致。</span></div><button className="primary" onClick={()=>start(core)}>继续今天学习 <ArrowRight/></button></>:<div className="empty-state"><h2>核心学习暂时完成</h2><p>可以打开 Learn 查看课程地图。</p><button onClick={()=>setView("learning")}><RotateCcw/> 打开学习</button></div>}</section>
      <section className="today-review"><span className="plan-label">B · Due Review</span>{due?<><Brain/><h2>{due.title}</h2><p>同一概念，不同表面特征。先回忆，再看反馈。</p><button onClick={()=>start(due)}>开始到期复习</button></>:<><CheckCircle2/><h2>今天没有到期复习</h2><p>未到期不是落后；间隔本身是学习设计的一部分。</p></>}</section>
      <section className="today-routine"><span className="plan-label">C · Research Routine</span><Lightbulb/><h2>AI 前先独立思考一次</h2><p>本周深读论文 {paperCount} / {state.routineSettings.weeklyPapers}。行为反馈不使用 streak 或惩罚性逾期。</p><div><button onClick={()=>setThinking(true)}>Think Before AI</button><button onClick={()=>state.papers[0]&&selectPaper(state.papers[0].id)}><BookOpen/> 本周论文</button><button className="subtle" onClick={()=>recordRoutine({routineType:"project_reflection",status:"partially_completed",projectId:state.projects[0]?.id})}>记录部分完成</button><button className="subtle" onClick={()=>recordRoutine({routineType:"project_reflection",status:"skipped",projectId:state.projects[0]?.id})}>今天跳过</button></div></section></div>
    {thinking&&<ThinkBeforeAi source="today" projectId={state.projects[0]?.id} onClose={()=>setThinking(false)}/>}</div>;
}
