import { FolderPlus, Link2, Plus } from "lucide-react";
import { useState } from "react";
import { ThinkBeforeAi } from "../../components/ThinkBeforeAi";
import type { Project } from "../../domain/types";
import { makeId } from "../../lib/ids";
import { useAppStore } from "../../state/store";

const blank = (): Omit<Project, "id" | "createdAt"> => ({ name: "", disease: "", studyType: "", cohort: "", omics: "", outcome: "", currentStage: "Planning", scientificQuestion: "", bottleneck: "", activeMethods: "", targetJournal: "", notes: "" });
const emptyStudio = { currentPhenomenon: "", currentEvidence: "", mainUncertainty: "", researchQuestion: "", competingExplanations: "", evidenceGap: "", nextMinimalAnalysis: "", expectedOutcomes: "", failureMode: "", validation: "", maximumClaim: "" };

function ProjectStudio({ projectId }: { projectId: string }) {
  const records = useAppStore((state) => state.projectStudioRecords.filter((record) => record.projectId === projectId));
  const save = useAppStore((state) => state.saveProjectStudioRecord);
  const createArtifact = useAppStore((state) => state.createTransferArtifact);
  const [form, setForm] = useState(emptyStudio);
  const fields: Array<[keyof typeof emptyStudio, string]> = [["currentPhenomenon", "Current phenomenon"], ["currentEvidence", "Current evidence"], ["mainUncertainty", "Main uncertainty"], ["researchQuestion", "Research question"], ["competingExplanations", "Competing explanations"], ["evidenceGap", "Evidence gap"], ["nextMinimalAnalysis", "Next minimal sufficient analysis"], ["expectedOutcomes", "Expected outcomes"], ["failureMode", "Failure mode"], ["validation", "Validation"], ["maximumClaim", "Maximum claim"]];
  const submit = () => {
    if (form.researchQuestion.trim().length < 8 || form.nextMinimalAnalysis.trim().length < 8) return;
    const recordId = save({ projectId, ...form });
    createArtifact({ sourceType: "project", sourceId: recordId, conceptIds: ["research-question", "evidence-claim"], capabilityIds: ["scientific_question", "result_interpretation", "next_step_design"], question: form.researchQuestion, userReasoning: `${form.currentEvidence}\n${form.competingExplanations}`, claimBoundary: form.maximumClaim, nextStep: form.nextMinimalAnalysis, linkedLearningEventIds: [] });
    setForm(emptyStudio);
  };
  return <section className="project-studio"><header><span className="eyebrow">Project Studio</span><h2>保留每次判断，而不是覆盖过去</h2></header><div className="project-studio-grid">{fields.map(([key, label]) => <label key={key}>{label}<textarea rows={2} value={form[key]} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))}/></label>)}</div><button className="primary" disabled={form.researchQuestion.trim().length < 8 || form.nextMinimalAnalysis.trim().length < 8} onClick={submit}>保存本次推理并生成 Transfer Artifact</button>{records.length > 0 && <details><summary>历史推理记录（{records.length}）</summary>{records.map((record) => <article key={record.id}><strong>{record.researchQuestion}</strong><p>{record.nextMinimalAnalysis}</p><small>{new Date(record.createdAt).toLocaleString("zh-CN")} · 最大主张：{record.maximumClaim || "未填写"}</small></article>)}</details>}</section>;
}

export function ProjectsView() {
  const projects = useAppStore((state) => state.projects), responses = useAppStore((state) => state.responses), records = useAppStore((state) => state.reasoningRecords);
  const addProject = useAppStore((state) => state.addProject), updateProject = useAppStore((state) => state.updateProject), notify = useAppStore((state) => state.notify);
  const [draft, setDraft] = useState(blank()), [selectedId, setSelectedId] = useState(projects[0]?.id), [creating, setCreating] = useState(projects.length === 0);
  const selected = projects.find((project) => project.id === selectedId), linked = selected ? responses.filter((response) => response.projectId === selected.id && response.transferText) : [], reasoning = selected ? records.filter((record) => record.projectId === selected.id) : [], editor = creating ? draft : selected;
  const change = (key: keyof Omit<Project, "id" | "createdAt">, value: string) => creating ? setDraft((current) => ({ ...current, [key]: value })) : selected && updateProject(selected.id, { [key]: value });
  const save = () => { if (draft.name.trim().length < 2 || draft.scientificQuestion.trim().length < 8) { notify("请填写项目名称和主要科学问题。", "warning"); return; } const project: Project = { ...draft, id: makeId("project"), createdAt: new Date().toISOString() }; addProject(project); setSelectedId(project.id); setCreating(false); setDraft(blank()); };
  return <div className="projects-layout"><aside className="project-list"><div className="pane-heading"><span>Projects</span><button onClick={() => setCreating(true)}><Plus/></button></div>{projects.map((project) => <button key={project.id} className={!creating && project.id === selectedId ? "active" : ""} onClick={() => { setSelectedId(project.id); setCreating(false); }}><FolderPlus/><span>{project.name}<small>{project.currentStage}</small></span></button>)}</aside><section className="project-editor scrollable"><header className="page-header compact"><div><span className="eyebrow">{creating ? "新建项目" : "Guided research apprenticeship"}</span><h1>{creating ? "定义真实研究情境" : selected?.name ?? "选择项目"}</h1><p>项目数据、推理历史和 Transfer Artifacts 只保存在本地。</p></div>{creating && <button className="primary" onClick={save}>创建项目</button>}</header>{editor ? <div className="project-form"><div className="form-grid two">{[["name", "项目名称"], ["disease", "疾病/现象"], ["studyType", "研究类型"], ["cohort", "队列/样本"], ["omics", "组学"], ["outcome", "结局"], ["activeMethods", "正在使用的方法"], ["targetJournal", "目标期刊"]].map(([key, label]) => <label key={key}>{label}<input value={String(editor[key as keyof typeof editor] ?? "")} onChange={(event) => change(key as keyof Omit<Project, "id" | "createdAt">, event.target.value)}/></label>)}</div><label>真正的科学问题<textarea rows={3} value={editor.scientificQuestion} onChange={(event) => change("scientificQuestion", event.target.value)}/></label><label>当前瓶颈<textarea rows={3} value={editor.bottleneck} onChange={(event) => change("bottleneck", event.target.value)}/></label><label>项目笔记<textarea rows={4} value={editor.notes} onChange={(event) => change("notes", event.target.value)}/></label></div> : <div className="empty-state"><h2>创建一个真实研究情境</h2></div>}{selected && !creating && <><ThinkBeforeAi source="project" projectId={selected.id}/><ProjectStudio projectId={selected.id}/><section className="linked-transfers"><h2>Reasoning records</h2>{reasoning.map((record) => <article key={record.id}><Link2/><div><strong>{record.question}</strong><p>{record.nextStep}</p><small>{new Date(record.createdAt).toLocaleString("zh-CN")}</small></div></article>)}{linked.map((response) => <article key={response.id}><Link2/><p>{response.transferText}</p></article>)}</section></>}</section></div>;
}
